version: '3.7'

services:
    redis:
        image: redis:5.0.7-alpine
        networks:
            - crm_infra
        volumes:
            - ../redis-data:/data

    web:
        build:
          context: ../
          dockerfile: infra/web/Dockerfile
        restart: always
        networks:
            - crm_infra
        ports:
            - "80:80"
        volumes:
            - ./web/web.conf:/etc/nginx/conf.d/default.conf

networks:
  crm_infra:
