version: 2.1
orbs:
  ansible: orbss/ansible-playbook@0.0.5

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
      #docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          key: v4-{{ .Branch }}          
      - run:
          name: Install some soft
          command: |
            sudo apt-get update && \
            sudo apt-get install libmysqlclient-dev -y
      - run:
          name: Build application
          command: |
            cd infra
            docker-compose build
      - run:
          name: Export images
          command: |
            cd infra
            mkdir bin_images
            docker image save infra_web:latest -o bin_images/web.tar
            ls -lh bin_images/web.tar
      - store_artifacts:
          path: infra/bin_images/web.tar
          destination: docker_images
      - save_cache:
          key: v4-{{ .Branch }}-{{ epoch }}
          paths:
            - /var/lib/docker/

  deploy:
    docker:
      - image: circleci/python
    parameters:
      inventory:
        type: env_var_name
        default: INVENTORY
      playbook:
        type: string
        default: ansible/playbook.yaml
      private-key:
        type: env_var_name
        default: SSH_KEY
      
    steps:
      - checkout
      - ansible/install:
          version: 2.9
      - ansible/galaxy:
          #galaxy-options: install
          galaxy-roles-path: community.docker
      - ansible/playbook:
          inventory: INVENTORY
          playbook: ansible/playbook.yaml
          private-key: SSH_KEY
      #    inventory: <<parameters.inventory>>
      #    playbook: <<parameters.playbook>>
      #    private-key: <<parameters.private-key>>
    #  - run:
    #      name: Install some soft
    #      command: |
    #        sudo apt-get update && \
    #        sudo apt-get install ansible -y
    #  - run:
    #      name: Test ansible
    #      command: |
    #        ansible --version
    #        ansible-playbook --version

workflows:
  version: 2.1
  workflow:
    jobs:
      #- build
      #- hold:
      #    type: approval
      #    requires:
      #      - build
      - deploy
          #requires:
          #  - build
            # - hold


# version: 2
# jobs:
#   build:
#     working_directory: /build_containers
#     docker:
#       - image: docker:20.10.1-git
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Install dependencies
#           command: | 
#             apk add docker-compose
#       - restore_cache:
#           keys:
#             - v1-{{ .Branch }}
#       - run:
#           name: Load Docker image layer cache
#           command: |
#             set +o pipefail
#             docker load -i /caches/build.tar | true
#       - run:
#           name: Build application
#           command: |
#             cd infra
#             docker-compose build
#       - save_cache:
#           key: v1-{{ .Branch }}-{{ epoch }}
#           paths:
#             - /caches/build.tar
# 
# workflows:
#   version: 2
#   workflow:
#     jobs:
#     - build
# 