version: 2
jobs:
  build:
    working_directory: /infra
    docker:
      - image: docker:20.10.1-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            apk add docker-compose
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/build.tar | true
      - run:
          name: Build application
          command: |
            pwd
            ls -l
            docker-compose build
      - run:
          name: Trying test up
          command: |
            docker-compose up

workflows:
  version: 2
  workflow:
    jobs:
    - build
