version: 2.1
orbs:
  ansible: orbss/ansible-playbook@0.0.5
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
      #docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          key: v4-{{ .Branch }}          
      - run:
          name: Install some soft
          command: |
            sudo apt-get update && \
            sudo apt-get install libmysqlclient-dev -y
      - run:
          name: Build application
          command: |
            cd infra
            docker-compose build
            docker image save infra_web:latest | gzip -9 -c > /tmp/web.tar.gz
      - store_artifacts:
          path: /tmp/web.tar.gz
          destination: docker_images
      - save_cache:
          key: v4-{{ .Branch }}-{{ epoch }}
          paths:
            - /var/lib/docker/

  deploy:
    docker:
      - image: docker:20.10.1-git
    #machine:
    #  image: ubuntu-2004:202010-01
    #  #docker_layer_caching: true
      
    steps:
      - checkout
      - ansible:
        inventory: INVENTORY
        playbook: ansible/playbook.yaml
        private-key: SSH_KEY
    #  - run:
    #      name: Install some soft
    #      command: |
    #        sudo apt-get update && \
    #        sudo apt-get install ansible -y
    #  - run:
    #      name: Test ansible
    #      command: |
    #        ansible --version
    #        ansible-playbook --version

workflows:
  version: 2.1
  workflow:
    jobs:
    #- build
    - deploy


# version: 2
# jobs:
#   build:
#     working_directory: /build_containers
#     docker:
#       - image: docker:20.10.1-git
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Install dependencies
#           command: | 
#             apk add docker-compose
#       - restore_cache:
#           keys:
#             - v1-{{ .Branch }}
#       - run:
#           name: Load Docker image layer cache
#           command: |
#             set +o pipefail
#             docker load -i /caches/build.tar | true
#       - run:
#           name: Build application
#           command: |
#             cd infra
#             docker-compose build
#       - save_cache:
#           key: v1-{{ .Branch }}-{{ epoch }}
#           paths:
#             - /caches/build.tar
# 
# workflows:
#   version: 2
#   workflow:
#     jobs:
#     - build
# 