version: 2.1
orbs:
  ansible: orbss/ansible-playbook@0.0.5

executors:
  build_machine:
    machine:
      image: ubuntu-2004:202010-01
      #docker_layer_caching: true

jobs:
  build:
    executor: build_machine
    steps:
      - checkout
      - restore_cache:
          key: v4-{{ .Branch }}          
      - run:
          name: Install some soft
          command: |
            sudo apt-get update && \
            sudo apt-get install libmysqlclient-dev -y
      - run:
          name: Build application
          command: |
            cd infra
            docker-compose build
      - run:
          name: Export images
          command: |
            cd infra
            mkdir bin_images
            docker image save infra_web:latest -o bin_images/web.tar
            ls -lh bin_images/web.tar
      - store_artifacts:
          path: infra/bin_images/web.tar
          destination: docker_images
      - save_cache:
          key: v4-{{ .Branch }}-{{ epoch }}
          paths:
            - /var/lib/docker/

  deploy:
    executor: build_machine
      
    steps:
      - checkout
      - run:
          name: Install some soft
          command: |
            sudo apt-get update
            sudo apt-get install ansible -y
            sudo pip3 install ansible
      - run:
          name: Test ansible
          command: |
            ansible --version
            ansible-playbook --version
      - run:
          name: Run ansible
          command: |
            cd ansible
            ansible-playbook -i inv playbook.yaml


workflows:
  version: 2.1
  workflow:
    jobs:
      - build
      - deploy
          requires:
            - build


# version: 2
# jobs:
#   build:
#     working_directory: /build_containers
#     docker:
#       - image: docker:20.10.1-git
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Install dependencies
#           command: | 
#             apk add docker-compose
#       - restore_cache:
#           keys:
#             - v1-{{ .Branch }}
#       - run:
#           name: Load Docker image layer cache
#           command: |
#             set +o pipefail
#             docker load -i /caches/build.tar | true
#       - run:
#           name: Build application
#           command: |
#             cd infra
#             docker-compose build
#       - save_cache:
#           key: v1-{{ .Branch }}-{{ epoch }}
#           paths:
#             - /caches/build.tar
# 
# workflows:
#   version: 2
#   workflow:
#     jobs:
#     - build
# 