---
- name: Test
  hosts: all
  gather_facts: no
  remote_user: ubuntu

  tasks:
    - name: ping
      ping:
        data: crush

    #- name: Add repository
    #  yum_repository:
    #    name: Docker CE Stable - $basearch
    #    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    #    enabled: 1
    #    gpgcheck: 1
    #    gpgkey: https://download.docker.com/linux/centos/gpg
    #    description: Docker CE
    #  become: yes
#
    #- name: Install docker engine
    #  yum:
    #    name:
    #      - docker-ce
    #      - docker-ce-cli
    #      - containerd.io
    #      - wget
    #      - python38
    #    state: present
    #  become: yes
#
    #- name: Install suggested packages
    #  yum:
    #    name:
    #      - wget
    #      - python38
    #      - python38-pip-wheel
    #    state: present
    #  become: yes
#
    - name: Install python packages
      pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: "/usr/local/sbin"
        mode: 0755
      become: yes

    - name: Download docker images
      shell: |
        curl -H 'Circle-Token: 210eac435a62fc7201da0b2a99eca3021983e625' https://circleci.com/api/v1.1/project/github/d-egiptyanin/docker-circle/latest/artifacts | \
        grep -o 'https://[^"]*' | \
        wget --verbose --header 'Circle-Token: $CIRCLE_TOKEN' --input-file - -O /tmp/web.tar

    - name: Load image from archive and push to a private registry
      community.docker.docker_image:
        name: infra_web
        tag: latest
        push: no
        load_path: /tmp/web.tar
        source: load
      become: yes

    - name: Setup docker-compose.yml
      shell: |
        echo "dmVyc2lvbjogJzMuNycKCnNlcnZpY2VzOgogICAgcmVkaXM6CiAgICAgICAgaW1hZ2U6IHJlZGlzOjUuMC43LWFscGluZQogICAgICAgIG5ldHdvcmtzOgogICAgICAgICAgICAtIGNybV9pbmZyYV9uZXcKICAgICAgICB2b2x1bWVzOgogICAgICAgICAgICAtIC4uL3JlZGlzLWRhdGE6L2RhdGEKCiAgICB3ZWI6CiAgICAgICAgYnVpbGQ6CiAgICAgICAgICBjb250ZXh0OiAuLi8KICAgICAgICAgIGRvY2tlcmZpbGU6IGluZnJhL3dlYi9Eb2NrZXJmaWxlCiAgICAgICAgcmVzdGFydDogYWx3YXlzCiAgICAgICAgbmV0d29ya3M6CiAgICAgICAgICAgIC0gY3JtX2luZnJhX25ldwogICAgICAgIHBvcnRzOgogICAgICAgICAgICAtICI4MDo4MCIKICAgICAgICB2b2x1bWVzOgogICAgICAgICAgICAtIC4vd2ViL3dlYi5jb25mOi9ldGMvbmdpbngvY29uZi5kL2RlZmF1bHQuY29uZgoKbmV0d29ya3M6CiAgY3JtX2luZnJhX25ldzoK" | \
        base64 -d > /tmp/docker-compose.yml

    - name: Run containers
      community.docker.docker_compose:
        project_src: /tmp/
        state: present
      become: yes
